edition = "2021"

fn_args_layout = "Vertical"
group_imports = "StdExternalCrate"
hard_tabs = true
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 120
chain_width = 120

# Unstable (Requires Rust nightly)
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
enum_discrim_align_threshold = 4
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
